# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/proto/login.proto
# Protobuf Python Version: 5.27.0-rc1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '-rc1',
    'protobuf/proto/login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotobuf/proto/login.proto\"\x1e\n\x0cLoginRequest\x12\x0e\n\x06UserID\x18\x01 \x01(\x04\"&\n\x0bLoginReplay\x12\x17\n\x03ret\x18\x01 \x01(\x0e\x32\n.LOGIN_RET*$\n\tLOGIN_RET\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.proto.login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGIN_RET']._serialized_start=102
  _globals['_LOGIN_RET']._serialized_end=138
  _globals['_LOGINREQUEST']._serialized_start=30
  _globals['_LOGINREQUEST']._serialized_end=60
  _globals['_LOGINREPLAY']._serialized_start=62
  _globals['_LOGINREPLAY']._serialized_end=100
# @@protoc_insertion_point(module_scope)
