// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 // generated by generate_mapping.py

// dont modify this file
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import { Player1 } from "./message/proto/test";
import { Player12 } from "./message/proto/test";
import { Player13 } from "./message/proto/test";
import { Player14 } from "./message/proto/test";
import { Player15 } from "./message/proto/test";
import { Player16 } from "./message/proto/test";
import { Player17 } from "./message/proto/test";
import { Player18 } from "./message/proto/test";
import { Player19 } from "./message/proto/test";
import { Player110 } from "./message/proto/test";

export const messageMappings = {
    1: Player1,
    2: Player12,
    3: Player13,
    4: Player14,
    5: Player15,
    6: Player16,
    7: Player17,
    8: Player18,
    9: Player19,
    10: Player110,
};

